Retriever:
  input_file_path: retriever/en_wiki_corpus.jsonl
  parameters:
    retrieval_chunk_size: 100
    retrieval_chunk_overlap: 30
    retrieval_top_k: 5
HybridRetriever:
  input_file_path: retriever/en_wiki_corpus.jsonl
  embedding_model_path: intfloat/multilingual-e5-large
  parameters:
    retrieval_chunk_size: 100
    retrieval_chunk_overlap: 30
    retrieval_top_k: 10
    reranking_top_k: 5
TriRetriever:
  input_file_path: retriever/en_wiki_corpus.jsonl
  embedding_model_path: intfloat/multilingual-e5-large
  parameters:
    retrieval_chunk_size: 100
    retrieval_chunk_overlap: 30
    retrieval_top_k: 10
    reranking_top_k: 5